//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationES
{
    using System;
    using System.Collections.Generic;
    
    public partial class emailData1
    {
        public string From1 { get; set; }
        public string To1 { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
    }
}
